insert into language (name) values ('English'),('German'),('French');
insert into country (name) values ('United Kingdom'),('Germany'),('France'),('Switzerland');

insert into source (name, homepage, language_id, country_id) values 
('BBC News',                'http://www.bbc.com/news', 1,1),
('Frankfurter Allgemeine',  'http://www.faz.net/', 2, 2),
('SRF',                     'http://www.srf.ch/news/', 2, 4),
('Franceinfo',              'http://www.francetvinfo.fr/', 3, 3);

insert into section (name, url, source_id) values
('Front page',              'http://www.bbc.com/news', 1),
('UK news',                 'http://www.bbc.com/news/uk', 1),
('World',                   'http://www.bbc.com/news/world', 1),
('Africa',                  'http://www.bbc.com/news/world/africa', 1),
('Asia',                    'http://www.bbc.com/news/world/asia', 1),
('Australia',               'http://www.bbc.com/news/world/australia', 1),
('Europe',                  'http://www.bbc.com/news/world/europe', 1),
('Latin America',           'http://www.bbc.com/news/world/latin_america', 1),
('Middle East',             'http://www.bbc.com/news/world/middle_east', 1),
('US & Canada',             'http://www.bbc.com/news/world/us_and_canada', 1),
('Business',                'http://www.bbc.com/news/business', 1),
('Technology',              'http://www.bbc.com/news/technology', 1),
('Science & Environment',   'http://www.bbc.com/news/science_and_environment', 1),
('Health',                  'http://www.bbc.com/news/health', 1),
('Entertainment & Arts',    'http://www.bbc.com/news/entertainment_and_arts', 1),


('Economy',                 'http://www.faz.net/aktuell/wirtschaft/', 2),
('Finances',                'http://www.faz.net/aktuell/finanzen/', 2),
('Feuilleton',              'http://www.faz.net/aktuell/feuilleton/', 2),
('Sport',                   'http://www.faz.net/aktuell/sport/', 2),
('Society',                 'http://www.faz.net/aktuell/gesellschaft/', 2),
('Style',                   'http://www.faz.net/aktuell/stil/', 2),
('Technology',              'http://www.faz.net/aktuell/technik-motor/', 2),
('Knowledge',               'http://www.faz.net/aktuell/wissen/', 2),
('Travel',                  'http://www.faz.net/aktuell/reise/', 2),
('Rhein-Main',              'http://www.faz.net/aktuell/rhein-main/', 2),


('Front page',              'http://www.srf.ch/news/', 3),
('Switzerland',             'http://www.srf.ch/news/schweiz', 3),
('Aargau Solothurn',        'http://www.srf.ch/news/regional/aargau-solothurn', 3),
('Basel Basel-Land',        'http://www.srf.ch/news/regional/basel-baselland', 3),
('Bern Fribourg Valais',    'http://www.srf.ch/news/regional/bern-freiburg-wallis', 3),
('Grisons',                 'http://www.srf.ch/news/regional/graubuenden', 3),
('East Switzerland',        'http://www.srf.ch/news/regional/ostschweiz', 3),
('Central Switzerland',     'http://www.srf.ch/news/regional/zentralschweiz', 3),
('Zurich & Schaffhausen',   'http://www.srf.ch/news/regional/zuerich-schaffhausen', 3),
('World',                   'http://www.srf.ch/news/international', 3),
('Panorama',                'http://www.srf.ch/news/panorama', 3),
('Economy',                 'http://www.srf.ch/news/wirtschaft', 3),
('Infographics',            'http://www.srf.ch/news/infografik-3', 3),
('Sport',                   'http://www.srf.ch/sport', 3),
('SRF Data',                'http://www.srf.ch/news/srf-data', 3),


('Front page',              'http://www.francetvinfo.fr/', 4),
('Politics',                'http://www.francetvinfo.fr/politique/', 4),
('Political affaires',      'http://www.francetvinfo.fr/politique/affaire/', 4),
('Various',                 'http://www.francetvinfo.fr/faits-divers/', 4),
('Society',                 'http://www.francetvinfo.fr/societe/', 4),
('Education',               'http://www.francetvinfo.fr/societe/education/', 4),
('Justice',                 'http://www.francetvinfo.fr/societe/justice/', 4),
('Nuclear',                 'http://www.francetvinfo.fr/societe/nucleaire/', 4),
('Economy',                 'http://www.francetvinfo.fr/economie/', 4),
('Auto',                    'http://www.francetvinfo.fr/economie/automobile/', 4),
('Aeroplane',               'http://www.francetvinfo.fr/economie/aeronautique/', 4),
('Commerce',                'http://www.francetvinfo.fr/economie/commerce/', 4),
('Telecom',                 'http://www.francetvinfo.fr/economie/telecom/', 4),
('Transport',               'http://www.francetvinfo.fr/economie/transports/', 4),
('World',                   'http://www.francetvinfo.fr/monde/', 4),
('Africa',                  'http://www.francetvinfo.fr/monde/afrique/', 4),
('France',                  'http://www.francetvinfo.fr/france/', 4),
('Americas',                'http://www.francetvinfo.fr/monde/ameriques/', 4),
('Asia',                    'http://www.francetvinfo.fr/monde/asie/', 4),
('Spain',                   'http://www.francetvinfo.fr/monde/espagne/', 4),
('Europe',                  'http://www.francetvinfo.fr/monde/europe/', 4),
('Greece',                  'http://www.francetvinfo.fr/monde/grece/', 4),
('Italy',                   'http://www.francetvinfo.fr/monde/italie/', 4),
('Netherlands',             'http://www.francetvinfo.fr/monde/pays-bas/', 4),
('Middle East',             'http://www.francetvinfo.fr/monde/proche-orient/', 4),
('UK',                      'http://www.francetvinfo.fr/monde/royaume-uni/', 4),
('Japan',                   'http://www.francetvinfo.fr/monde/japon/', 4),
('China',                   'http://www.francetvinfo.fr/monde/chine/', 4),
('Algeria',                 'http://www.francetvinfo.fr/monde/algerie/', 4),
('Russia',                  'http://www.francetvinfo.fr/monde/russie/', 4),
('North Korea',             'http://www.francetvinfo.fr/monde/coree-du-nord/', 4),
('Egypt',                   'http://www.francetvinfo.fr/monde/egypte/', 4),
('USA',                     'http://www.francetvinfo.fr/monde/usa/', 4),
('Vatican',                 'http://www.francetvinfo.fr/monde/vatican/', 4),
('Culture',                 'http://www.francetvinfo.fr/culture/', 4),
('Sport',                   'http://www.francetvinfo.fr/sports/', 4),
('Health',                  'http://www.francetvinfo.fr/sante/', 4),
('Science',                 'http://www.francetvinfo.fr/sciences/', 4),
('Archeology',              'http://www.francetvinfo.fr/sciences/archeologie/', 4),
('Astronomy',               'http://www.francetvinfo.fr/sciences/astronomie/', 4),
('Space',                   'http://www.francetvinfo.fr/sciences/espace/', 4),
('History',                 'http://www.francetvinfo.fr/sciences/histoire/', 4),
('Scientific Discoveries',  'http://www.francetvinfo.fr/sante/decouverte-scientifique/', 4),
('Technology / Web',        'http://www.francetvinfo.fr/internet/', 4),
('Animals',                 'http://www.francetvinfo.fr/animaux/', 4),
('Endangered Species',      'http://www.francetvinfo.fr/animaux/especes-menacees/', 4);
#46

insert into parse_rule (section_id, css_selector, text_tag, exclude_urls) values
(1,  '.gs-c-promo-heading', 'h3',    'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(2,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(3,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(4,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(5,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(6,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(7,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(8,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(9,  '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(10, '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(11, '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(12, '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(13, '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(14, '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),
(15, '.title-link__title', 'self_parent', 'http://www.bbc.co.uk/events/*;http://www.bbc.com/earth/uk;http://www.bbc.co.uk/science;http://www.bbc.com/future'),


(16, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(17, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(18, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(19, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(20, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(21, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(22, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(23, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(24, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),
(25, '.TeaserHeadLink', null, 'http://www.faz.net/op900/event/*;http://www.faz.net/epaper;http://www.faz.net/aktuell/gesellschaft/jugend-schreibt/;http://www.faz.net/aktuell/feuilleton/pop/album-der-woche/;http://www.faz.net/op900/event/europa-league/live/;http://www.faz.net/gastspezial;http://blogs.faz.net/foodaffair/*;http://www.faz.net/plus;http://plus.faz.net/*;http://eix.faz.net/*;http://quelleinternet.faz.net/*;http://event.faz.net/*;http://dynamic.faz.net/*;http://www.fnp.de/fnp/anzeigen/trauerportal/;http://www.faz-leser-helfen.de/die-stiftung/f-a-z-leser-helfen-hier-koennen-sie-spenden-13086256.html;http://www.facebook.com/*;http://www.twitter.com/*;https://www.facebook.com/*;https://www.twitter.com/*;http://foursquare.com/*;https://www.faz.net/mein-faz-net/newsletter/;http://www.faz.net/aktuell/finanzen/boersenspiel/'),


(27, '.title', 'self_parent', null),
(28, '.title', 'self_parent', null),
(29, '.title', 'self_parent', null),
(30, '.title', 'self_parent', null),
(31, '.title', 'self_parent', null),
(32, '.title', 'self_parent', null),
(33, '.title', 'self_parent', null),
(34, '.title', 'self_parent', null),
(35, '.title', 'self_parent', null),
(36, '.title', 'self_parent', null),
(37, '.title', 'self_parent', null),
(38, '.title', 'self_parent', null),
(39, '.title', 'self_parent', null),
(40, '.title', 'self_parent', null),


(41, '.col-2 a', 'self_parent', 'https://www.facebook.com/*;https://twitter.com/*;https://plus.google.com/*;https://www.youtube.com/*;https://www.instagram.com/*;https://www.snapchat.com/*;http://www.francetvinfo.fr/rss/;https://play.google.com/*;https://itunes.apple.com/*');
# up to 86 inclusive